management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        namespaces: default

  main:
    cloud-platform: kubernetes

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: "{cipher}7e56ce72ef2bd5948b8870cdba2d3cf2f959539aef9ba3b5995b32647ecbdb8c"
    password: "{cipher}d7707f6bb565630936b4e1859330420c87b66305c75476a2f190318de02dd9b8"

rabbitmq:
  exchanges:
    user: user.exchange
    post: post.exchange
    comment: comment.exchange

  queues:
    user:
      created: user.created.queue
      deleted: user.deleted.queue
      updated: user.updated.queue
    post:
      created: post.created.queue
      deleted: post.deleted.queue
    comment:
      created: comment.created.queue
      deleted: comment.deleted.queue

  routing-keys:
    user:
      created: user.created
      deleted: user.deleted
      updated: user.updated
    post:
      created: post.created
      deleted: post.deleted
    comment:
      created: comment.created
      deleted: comment.deleted
