management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true

rabbitmq:
  exchanges:
    user: user.exchange
    post: post.exchange

  queues:
    user:
      created: user.created.queue
      deleted: user.deleted.queue
      updated: user.updated.queue
    post:
      created: post.created.queue
      deleted: post.deleted.queue

  routing-keys:
    user:
      created: user.created
      deleted: user.deleted
      updated: user.updated
    post:
      created: post.created
      deleted: post.deleted
