spring:
  # 나중에 mariadb 로 변경
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://192.168.192.2:8080/login/oauth2/code/kakao

  # 나중에 배포용 redis 서버 지정
  data:
    redis:
      host: localhost
      port: 6379
